# Generated by Django 4.2.1 on 2023-05-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_pdf_cert', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cert',
            options={'ordering': ('-created',), 'verbose_name_plural': 'Certificates'},
        ),
        migrations.AddField(
            model_name='cert',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
